const productdetail = [
    {
        id: 1,
        Quantity: 1,
        name: 'T-shirt',
        price: '30.00',
        size: 'S, M , L , XL , XXL',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/img1.webp',
        material: 'Cotton fabric',
        category: 'men',
    },
    {
        id: 2,
        Quantity: 1,
        name: 'T-shirt',
        price: '40.00',
        size: 'S, M , L , XL , XXL',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/img2.webp',
        material: 'Cotton fabric',
        category: 'men',
    },
    {
        id: 3,
        Quantity: 1,
        name: 'T-shirt',
        price: '50.00',
        size: 'S, M , L , XL , XXL',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/img3.webp',
        material: 'Cotton fabric',
        category: 'men',
    },
    {
        id: 4,
        Quantity: 1,
        name: 'T-shirt',
        price: '30.00',
        size: 'S, M , L , XL , XXL',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/img1.webp',
        material: 'Cotton fabric',
        category: 'men',
    },
    {
        id: 5,
        Quantity: 1,
        name: 'POCO M4 5G',
        price: '10000.00',
        size: '32 GB , 64 GB',
        description:
            'This phone comes loaded with the Dimensity 700 processor, UFS 2.2 WriteBooster, and up to 2 GB of Turbo RAM',
        image: '/shopping/img6.webp',
        ModelNumber: 'MZB0BRXIN',
        category: 'mobile',
    },
    {
        id: 6,
        Quantity: 1,
        name: 'Realme C30',
        price: '5000.00',
        size: '32 GB , 64 GB',
        description:
            '8MP Rear Camera | 5MP Front Camera , 16.51 cm (6.5 inch) HD+ Display',
        image: '/shopping/img5.webp',
        ModelNumber: 'RMX3581',
        category: 'mobile',
    },
    {
        id: 7,
        Quantity: 1,
        name: 'POCO M4 5G',
        price: '10000.00',
        size: '32 GB , 64 GB',
        description:
            'This phone comes loaded with the Dimensity 700 processor, UFS 2.2 WriteBooster, and up to 2 GB of Turbo RAM',
        image: '/shopping/img6.webp',
        ModelNumber: 'MZB0BRXIN',
        category: 'mobile',
    },
    {
        id: 8,
        Quantity: 1,
        name: 'APPLE iPhone 13 ',
        price: '70000.00',
        size: '64 GB , 128 GB',
        description: '15.49 cm (6.1 inch) Super Retina XDR Display',
        image: '/shopping/img8.webp',
        ModelNumber: 'MLPG3HN/A',
        category: 'mobile',
    },
    {
        id: 9,
        Quantity: 1,
        name: 'APPLE iPhone 13 ',
        price: '65000.00',
        size: '64 GB , 128 GB',
        description: '15.49 cm (6.1 inch) Super Retina XDR Display',
        image: '/shopping/img9.webp',
        ModelNumber: 'MLPG3HN/A',
        category: 'mobile',
    },
    {
        id: 10,
        Quantity: 1,
        name: ' Boys Analog Watch',
        price: '300.00',
        size: 'Small , Big',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/img10.webp',
        ModelNumber: 'LCS-8188',
        category: 'watch',
    },
    {
        id: 11,
        Quantity: 1,
        name: ' Dark Blue Jeans',
        price: '400.00',
        size: '28,30,32,34',
        description: 'Good quality product ',
        image: '/shopping/img11.webp',
        material: 'Cotton fabric',
        category: 'men',
    },
    {
        id: 12,
        Quantity: 1,
        name: ' Light Black Jeans',
        price: '500.00',
        size: '28,30,32,34',
        description: 'Good quality product ',
        image: '/shopping/img12.webp',
        material: 'Cotton fabric',
        category: 'men',
    },

    {
        id: 13,
        Quantity: 1,
        name: 'Laptop',
        price: '50000.00',
        size: '8 GB RAM',
        description: 'Laptop, Power Adaptor, User Guide, Warranty Documents',
        image: '/shopping/laptop1.jpg',
        ModelNumber: 'LCS-8188',
        category: 'laptop',
    },
    {
        id: 14,
        Quantity: 1,
        name: 'Gameing Laptop',
        price: '70000.00',
        size: '16 GB RAM',
        description: 'Laptop, Power Adaptor, User Guide, Warranty Documents',
        image: '/shopping/laptop2.jpg',
        ModelNumber: 'LCS-8188',
        category: 'laptop',
    },
    {
        id: 15,
        Quantity: 1,
        name: 'Gameing Laptop',
        price: '70000.00',
        size: '16 GB RAM',
        description: 'Laptop, Power Adaptor, User Guide, Warranty Documents',
        image: '/shopping/laptop3.jpg',
        ModelNumber: 'LCS-8188',
        category: 'laptop',
    },
    {
        id: 16,
        Quantity: 1,
        name: 'Gameing Laptop',
        price: '70000.00',
        size: '16 GB RAM',
        description: 'Laptop, Power Adaptor, User Guide, Warranty Documents',
        image: '/shopping/laptop4.jpg',
        ModelNumber: 'LCS-8188',
        category: 'laptop',
    },
    {
        id: 17,
        Quantity: 1,
        name: ' Boys Analog Watch',
        price: '4300.00',
        size: 'Small , Big',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/watch1.jpg',
        ModelNumber: 'LCS-8188',
        category: 'watch',
    },
    {
        id: 18,
        Quantity: 1,
        name: ' Boys Smart Watch',
        price: '3300.00',
        size: 'Small , Big',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/watch2.jpg',
        ModelNumber: 'LCS-8188',
        category: 'watch',
    },
    {
        id: 19,
        Quantity: 1,
        name: ' Boys Bands Watch',
        price: '1300.00',
        size: 'Small , Big',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/watch3.jpg',
        ModelNumber: 'LCS-8188',
        category: 'watch',
    },
    {
        id: 20,
        Quantity: 1,
        name: ' Boys Analog Watch',
        price: '1500.00',
        size: 'Small , Big',
        description: 'Men Color Block Round Neck White, Black T-Shirt',
        image: '/shopping/watch4.jpg',
        ModelNumber: 'LCS-8188',
        category: 'watch',
    },
];

export default productdetail;
